name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: espresso-rails-test_test
          MYSQL_USER: espresso
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update RubyGems
      run: |
        gem install rubygems-update -v 3.3.22
        update_rubygems
        gem --version

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.8'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Rubocop
      run: |
        bundle exec rubocop

    - name: Setup Database
      run: |
        RAILS_ENV=test bundle exec rails db:setup

    - name: Run RSpec
      run: |
        bundle exec rspec

    - name: Simplecov Report
      uses: joshmfrankel/simplecov-check-action@main
      with:
        minimum_suite_coverage: 99
        minimum_file_coverage: 99
        github_token: ${{ secrets.GITHUB_TOKEN }}
